server:
  port: 8001

spring:
  application:
    name: guns-cloud-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guns_cloud_system?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    username: root
    password: EUrD9jIZtEQf8G9r
  redis:
    host: 127.0.0.1
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
        register-enabled: true
        watch-delay: 1000

ribbon:
  eager-load:
    enabled: true
    # 多个服务用逗号隔开
    clients: roses-account

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 500  #连接超时时间
        readTimeout: 5000    #连接超时时间
        errorDecoder: cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignErrorDecoder
        requestInterceptors:
          - cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignHeaderProcessInterceptor
  #        retryer: com.xx.xx.Simple #重试策略
  #        encoder: com.xx.xx.Simple #编码器
  #        decoder: com.xx.xx.Simple #解码器
  #        contract: com.xx.xx.Simple #契约
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

mybatis-plus:
  mapper-locations:
    - classpath*:cn/stylefeng/guns/cloud/system/modular/**/mapping/*.xml
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

# 请求鉴权token的密钥，默认过期时间1天，单位：秒
jwt:
  secret: HMk60Cww2Z4toC8kS2HDa9j1ObJgGV8a
  expiration: 86400

roses:
  scanner:
    app-code: guns-cloud-system
    app-name: Cloud系统管理
    open: true
  tenant:
    open: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# 文件存储服务器
file:
  access-key: admin
  secret-key: abcd1234
  default-bucket: gunsfilesystem
  server-endpoint: http://localhost:9777
  external-server-endpoint: http://localhost:9777
  expire-seconds: 3600