server:
  port: ${SERVER_PORT}
  max-http-header-size: 10240

beetl:
  #热加载beetl模板，开发时候用
  resource-auto-check: true

spring:
  application:
    name: guns-cloud-auth
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    filters: wall,mergeStat
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  mvc:
    view:
      prefix: /pages
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: ${REGISTER_HOST}
        enabled: true
        register-enabled: true
        watch-delay: 1000

mybatis-plus:
  typeAliasesPackage: cn.stylefeng.dca.modular.system.model
  mapper-locations: classpath:cn/stylefeng/guns/cloud/auth/modular/**/mapping/*.xml

ribbon:
  eager-load:
    enabled: true
    # 多个服务用逗号隔开
    clients: roses-account

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        # NONE不记录任何日志--BASIC仅请求方法URL,状态码执行时间等--HEADERS在BASIC基础上记录header等--FULL记录所有
        loggerLevel: full
        connectTimeout: 500  #连接超时时间
        readTimeout: 5000    #连接超时时间
        errorDecoder: cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignErrorDecoder
        requestInterceptors:
          - cn.stylefeng.guns.cloud.libs.cloud.feign.GunsFeignHeaderProcessInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

roses:
  scanner:
    app-code: guns-cloud-auth
    app-name: 认证中心系统
    open: true
  tenant:
    open: false

#配置获取网关相关信息的路由
gatewayInfo:
  path:
    routes: http://${GATEWAY_HOST}/actuator/gateway/routes #网关路由列表
    globalfilters: http://${GATEWAY_HOST}/actuator/gateway/globalfilters #过滤器列表
    routefilters: http://${GATEWAY_HOST}/actuator/gateway/routefilters #所有的过滤器工厂列表
    routeInfoById: http://${GATEWAY_HOST}/actuator/gateway/routes/ #根据id查询路由信息
    refresh: http://${GATEWAY_HOST}/actuator/gateway/refresh #清空路由缓存
    addRoute: http://${GATEWAY_HOST}/actuator/gateway/routes/ #新增路由
    deleteRoute: http://${GATEWAY_HOST}/actuator/gateway/routes/ #删除指定路由